// <auto-generated />
using System;
using MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Đồ_án_ngành.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825100036_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MODEL.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SoBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaBan");

                    b.HasIndex("SoBan")
                        .IsUnique();

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("MODEL.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaChiTietHoaDon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("MODEL.ChiTietKhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("MaKhuyenMai", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietKhuyenMai");
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaChiTietPN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietPN");

                    b.HasIndex("MaNVL");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaTopping");

                    b.ToTable("ChiTietPhieuNhap");

                    b.HasCheckConstraint("CK_ChiTietPhieuNhap_LoaiHang", @"([MaNVL] IS NOT NULL AND [MaTopping] IS NULL)
                    OR
                    ([MaNVL] IS NULL AND [MaTopping] IS NOT NULL)");
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuXuat", b =>
                {
                    b.Property<string>("MaChiTietPX")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaPhieuXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietPX");

                    b.HasIndex("MaNVL");

                    b.HasIndex("MaPhieuXuat");

                    b.HasIndex("MaTopping");

                    b.ToTable("ChiTietPhieuXuat");

                    b.HasCheckConstraint("CK_ChiTietPhieuXuat_LoaiHang", @"([MaNVL] IS NOT NULL AND [MaTopping] IS NULL)
                    OR
                    ([MaNVL] IS NULL AND [MaTopping] IS NOT NULL)");
                });

            modelBuilder.Entity("MODEL.ChiTietTopping", b =>
                {
                    b.Property<string>("MaChiTietHoaDon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietHoaDon", "MaTopping");

                    b.HasIndex("MaTopping");

                    b.ToTable("ChiTietTopping");
                });

            modelBuilder.Entity("MODEL.CongThuc", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("DinhLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaMon", "MaNVL");

                    b.HasIndex("MaNVL");

                    b.ToTable("CongThuc");
                });

            modelBuilder.Entity("MODEL.DanhMuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("TenDanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("MODEL.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaBan")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaPhuongThuc")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienKhachDua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienThoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhuongThuc");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("MODEL.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("MaKH");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("MODEL.KhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiaTriKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("MODEL.Mon", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaMon");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("TenMon")
                        .IsUnique();

                    b.ToTable("Mon");
                });

            modelBuilder.Entity("MODEL.NguyenVatLieu", b =>
                {
                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("MucCanhBao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNVL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaNVL");

                    b.HasIndex("TenNVL")
                        .IsUnique();

                    b.ToTable("NguyenVatLieu");
                });

            modelBuilder.Entity("MODEL.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("MaNCC");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.HasIndex("TenNCC")
                        .IsUnique();

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("MODEL.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("MaNV");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("MODEL.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNCC");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("MODEL.PhieuXuat", b =>
                {
                    b.Property<string>("MaPhieuXuat")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LyDoXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuXuat");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("MODEL.PhuongThucThanhToan", b =>
                {
                    b.Property<string>("MaPhuongThuc")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("LaTienMat")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaPhuongThuc");

                    b.ToTable("PhuongThucThanhToan");
                });

            modelBuilder.Entity("MODEL.Topping", b =>
                {
                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MucCanhBao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaTopping");

                    b.HasIndex("TenTopping")
                        .IsUnique();

                    b.ToTable("Topping");
                });

            modelBuilder.Entity("MODEL.ChiTietHoaDon", b =>
                {
                    b.HasOne("MODEL.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Mon", "Mon")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("MODEL.KhuyenMai", "KhuyenMai")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Mon", "Mon")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("MODEL.NguyenVatLieu", "NguyenVatLieu")
                        .WithMany()
                        .HasForeignKey("MaNVL")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("MaTopping")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("MODEL.NguyenVatLieu", "NguyenVatLieu")
                        .WithMany()
                        .HasForeignKey("MaNVL")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("MaTopping")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.ChiTietTopping", b =>
                {
                    b.HasOne("MODEL.ChiTietHoaDon", "ChiTietHoaDon")
                        .WithMany("ChiTietToppings")
                        .HasForeignKey("MaChiTietHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("MaTopping")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.CongThuc", b =>
                {
                    b.HasOne("MODEL.Mon", "Mon")
                        .WithMany("CongThucs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.NguyenVatLieu", "NguyenVatLieu")
                        .WithMany("CongThucs")
                        .HasForeignKey("MaNVL")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.HoaDon", b =>
                {
                    b.HasOne("MODEL.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany()
                        .HasForeignKey("MaPhuongThuc")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.Mon", b =>
                {
                    b.HasOne("MODEL.DanhMuc", "DanhMuc")
                        .WithMany("Mons")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.PhieuNhap", b =>
                {
                    b.HasOne("MODEL.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
