// <auto-generated />
using System;
using MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Đồ_án_ngành.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908075944_ThemGiaTriChiTietPhieuXuat")]
    partial class ThemGiaTriChiTietPhieuXuat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MODEL.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SoBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaBan");

                    b.HasIndex("SoBan")
                        .IsUnique();

                    b.ToTable("Ban");

                    b.HasData(
                        new
                        {
                            MaBan = "B001",
                            SoBan = "1",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B002",
                            SoBan = "2",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B003",
                            GhiChu = "Kiểm tra bàn",
                            SoBan = "3",
                            TrangThai = "Đang bảo trì"
                        },
                        new
                        {
                            MaBan = "B004",
                            SoBan = "4",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B005",
                            SoBan = "5",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B006",
                            SoBan = "6",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B007",
                            SoBan = "7",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B008",
                            SoBan = "8",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B009",
                            SoBan = "9",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B010",
                            SoBan = "10",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B011",
                            SoBan = "11",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B012",
                            SoBan = "12",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B013",
                            SoBan = "13",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B014",
                            SoBan = "14",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B015",
                            SoBan = "15",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B016",
                            SoBan = "16",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B017",
                            SoBan = "17",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B018",
                            SoBan = "18",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B019",
                            SoBan = "19",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B020",
                            SoBan = "20",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B021",
                            SoBan = "21",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B022",
                            SoBan = "22",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B023",
                            SoBan = "23",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B024",
                            SoBan = "24",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B025",
                            SoBan = "25",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B026",
                            SoBan = "26",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B027",
                            SoBan = "27",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B028",
                            SoBan = "28",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B029",
                            SoBan = "29",
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaBan = "B030",
                            SoBan = "30",
                            TrangThai = "Trống"
                        });
                });

            modelBuilder.Entity("MODEL.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaChiTietHoaDon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaTopping");

                    b.ToTable("ChiTietHoaDon");

                    b.HasCheckConstraint("CK_ChiTietHoaDon_LoaiHang", "([MaMon] IS NOT NULL AND [MaTopping] IS NULL) OR ([MaMon] IS NULL AND [MaTopping] IS NOT NULL)");
                });

            modelBuilder.Entity("MODEL.ChiTietKhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("MaKhuyenMai", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietKhuyenMai");
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaChiTietPN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietPN");

                    b.HasIndex("MaNVL");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaTopping");

                    b.ToTable("ChiTietPhieuNhap");

                    b.HasCheckConstraint("CK_ChiTietPhieuNhap_LoaiHang", @"([MaNVL] IS NOT NULL AND [MaTopping] IS NULL)
                    OR
                    ([MaNVL] IS NULL AND [MaTopping] IS NOT NULL)");
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuXuat", b =>
                {
                    b.Property<string>("MaChiTietPX")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaPhieuXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietPX");

                    b.HasIndex("MaNVL");

                    b.HasIndex("MaPhieuXuat");

                    b.HasIndex("MaTopping");

                    b.ToTable("ChiTietPhieuXuat");

                    b.HasCheckConstraint("CK_ChiTietPhieuXuat_LoaiHang", @"([MaNVL] IS NOT NULL AND [MaTopping] IS NULL)
                    OR
                    ([MaNVL] IS NULL AND [MaTopping] IS NOT NULL)");
                });

            modelBuilder.Entity("MODEL.CongThuc", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("DinhLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaMon", "MaNVL");

                    b.HasIndex("MaNVL");

                    b.ToTable("CongThuc");
                });

            modelBuilder.Entity("MODEL.DanhMuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("TenDanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            MaDanhMuc = "DM001",
                            TenDanhMuc = "Cà phê"
                        },
                        new
                        {
                            MaDanhMuc = "DM002",
                            TenDanhMuc = "Trà sữa"
                        },
                        new
                        {
                            MaDanhMuc = "DM003",
                            TenDanhMuc = "Trà"
                        },
                        new
                        {
                            MaDanhMuc = "DM004",
                            TenDanhMuc = "Bánh"
                        });
                });

            modelBuilder.Entity("MODEL.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaBan")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaPhuongThuc")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienKhachDua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienThoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhuongThuc");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("MODEL.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("MaKH");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKH = "KH001",
                            DiemTichLuy = 20,
                            HoTen = "Nguyễn Văn A",
                            NgaySinh = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0900000001"
                        },
                        new
                        {
                            MaKH = "KH002",
                            DiemTichLuy = 10,
                            HoTen = "Trần Thị B",
                            NgaySinh = new DateTime(2001, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0900000002"
                        });
                });

            modelBuilder.Entity("MODEL.KhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("GiaTriKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KhuyenMai");

                    b.HasData(
                        new
                        {
                            MaKhuyenMai = "KM001",
                            GiaTriKhuyenMai = 20m,
                            LoaiKhuyenMai = "Phần trăm",
                            NgayBatDau = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenKhuyenMai = "Giảm 20% trà sữa",
                            TrangThai = "Đang áp dụng"
                        });
                });

            modelBuilder.Entity("MODEL.Mon", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaMon");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("TenMon")
                        .IsUnique();

                    b.ToTable("Mon");

                    b.HasData(
                        new
                        {
                            MaMon = "M001",
                            GiaBan = 25000m,
                            MaDanhMuc = "DM001",
                            TenMon = "Cà phê đen",
                            TrangThai = "Đang bán"
                        },
                        new
                        {
                            MaMon = "M002",
                            GiaBan = 30000m,
                            MaDanhMuc = "DM001",
                            TenMon = "Cà phê sữa",
                            TrangThai = "Đang bán"
                        },
                        new
                        {
                            MaMon = "M003",
                            GiaBan = 39000m,
                            MaDanhMuc = "DM002",
                            TenMon = "Matcha Latte",
                            TrangThai = "Đang bán"
                        },
                        new
                        {
                            MaMon = "M004",
                            GiaBan = 35000m,
                            MaDanhMuc = "DM003",
                            TenMon = "Trà đào",
                            TrangThai = "Đang bán"
                        },
                        new
                        {
                            MaMon = "M005",
                            GiaBan = 45000m,
                            MaDanhMuc = "DM004",
                            TenMon = "Tiramisu",
                            TrangThai = "Đang bán"
                        });
                });

            modelBuilder.Entity("MODEL.NguyenVatLieu", b =>
                {
                    b.Property<string>("MaNVL")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("MucCanhBao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNVL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaNVL");

                    b.HasIndex("TenNVL")
                        .IsUnique();

                    b.ToTable("NguyenVatLieu");

                    b.HasData(
                        new
                        {
                            MaNVL = "NVL001",
                            DonViTinh = "g",
                            MucCanhBao = 500m,
                            SoLuongTon = 5000m,
                            TenNVL = "Cà phê",
                            TrangThai = "Còn hàng"
                        },
                        new
                        {
                            MaNVL = "NVL002",
                            DonViTinh = "ml",
                            MucCanhBao = 1000m,
                            SoLuongTon = 10000m,
                            TenNVL = "Sữa",
                            TrangThai = "Còn hàng"
                        },
                        new
                        {
                            MaNVL = "NVL003",
                            DonViTinh = "g",
                            MucCanhBao = 100m,
                            SoLuongTon = 1000m,
                            TenNVL = "Matcha",
                            TrangThai = "Còn hàng"
                        },
                        new
                        {
                            MaNVL = "NVL004",
                            DonViTinh = "cái",
                            MucCanhBao = 5m,
                            SoLuongTon = 20m,
                            TenNVL = "Bánh Tiramisu",
                            TrangThai = "Còn hàng"
                        });
                });

            modelBuilder.Entity("MODEL.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("MaNCC");

                    b.HasIndex("SDT")
                        .IsUnique();

                    b.HasIndex("TenNCC")
                        .IsUnique();

                    b.ToTable("NhaCungCap");

                    b.HasData(
                        new
                        {
                            MaNCC = "NCC001",
                            DiaChi = "TP.HCM",
                            Email = "ncca@example.com",
                            SDT = "0911111111",
                            TenNCC = "Nhà cung cấp A"
                        },
                        new
                        {
                            MaNCC = "NCC002",
                            DiaChi = "TP.HCM",
                            Email = "nccb@example.com",
                            SDT = "0922222222",
                            TenNCC = "Nhà cung cấp B"
                        });
                });

            modelBuilder.Entity("MODEL.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("MaNV");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNV = "NV001",
                            ChucVu = "Cashier 1",
                            MatKhau = "123456",
                            TenDangNhap = "Cash1"
                        },
                        new
                        {
                            MaNV = "NV002",
                            ChucVu = "Cashier 2",
                            MatKhau = "123456",
                            TenDangNhap = "Cash2"
                        },
                        new
                        {
                            MaNV = "NV003",
                            ChucVu = "Manager",
                            MatKhau = "123456",
                            TenDangNhap = "Manager"
                        });
                });

            modelBuilder.Entity("MODEL.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNCC");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("MODEL.PhieuXuat", b =>
                {
                    b.Property<string>("MaPhieuXuat")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("LaHaoHut")
                        .HasColumnType("bit");

                    b.Property<string>("LyDoXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuXuat");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("MODEL.PhuongThucThanhToan", b =>
                {
                    b.Property<string>("MaPhuongThuc")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("LaTienMat")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("MaPhuongThuc");

                    b.ToTable("PhuongThucThanhToan");

                    b.HasData(
                        new
                        {
                            MaPhuongThuc = "PT01",
                            LaTienMat = true,
                            TenPhuongThuc = "Tiền mặt"
                        },
                        new
                        {
                            MaPhuongThuc = "PT02",
                            LaTienMat = false,
                            TenPhuongThuc = "Chuyển khoản"
                        },
                        new
                        {
                            MaPhuongThuc = "PT03",
                            LaTienMat = false,
                            TenPhuongThuc = "Thẻ"
                        });
                });

            modelBuilder.Entity("MODEL.Topping", b =>
                {
                    b.Property<string>("MaTopping")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MucCanhBao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("MaTopping");

                    b.HasIndex("TenTopping")
                        .IsUnique();

                    b.ToTable("Topping");

                    b.HasData(
                        new
                        {
                            MaTopping = "TP001",
                            DonViTinh = "phần",
                            GiaBan = 10000m,
                            MucCanhBao = 5m,
                            SoLuongTon = 30m,
                            TenTopping = "Pudding",
                            TrangThai = "Đang bán"
                        },
                        new
                        {
                            MaTopping = "TP002",
                            DonViTinh = "phần",
                            GiaBan = 8000m,
                            MucCanhBao = 5m,
                            SoLuongTon = 40m,
                            TenTopping = "Thạch",
                            TrangThai = "Đang bán"
                        });
                });

            modelBuilder.Entity("MODEL.ChiTietHoaDon", b =>
                {
                    b.HasOne("MODEL.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Mon", "Mon")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("MaTopping")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("MODEL.KhuyenMai", "KhuyenMai")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Mon", "Mon")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("MODEL.NguyenVatLieu", "NguyenVatLieu")
                        .WithMany()
                        .HasForeignKey("MaNVL")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("MaTopping")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("MODEL.NguyenVatLieu", "NguyenVatLieu")
                        .WithMany()
                        .HasForeignKey("MaNVL")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("MaTopping")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.CongThuc", b =>
                {
                    b.HasOne("MODEL.Mon", "Mon")
                        .WithMany("CongThucs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.NguyenVatLieu", "NguyenVatLieu")
                        .WithMany("CongThucs")
                        .HasForeignKey("MaNVL")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.HoaDon", b =>
                {
                    b.HasOne("MODEL.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MODEL.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MODEL.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany()
                        .HasForeignKey("MaPhuongThuc")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MODEL.Mon", b =>
                {
                    b.HasOne("MODEL.DanhMuc", "DanhMuc")
                        .WithMany("Mons")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MODEL.PhieuNhap", b =>
                {
                    b.HasOne("MODEL.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
